### ISSUE TITLE
Remove backward compatibility workaround for old PHPUnit versions

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/diff#100]
`Differ::__construct()` should only accept `DiffOutputBuilderInterface` arguments, #66 needs to be reverted. This breaks backward compatibility and must wait for the next major version.

**Comment by SpacePossum** [comment]
@sebastianbergmann feel free to ping me here if you want me to prepare a PR

**Comment by sebastianbergmann** [comment]
Thank you, @SpacePossum, for offering but I will do this myself when "the time is right".
