### ISSUE TITLE
[Feature] Percent change

### ISSUE THREAD

**Issue by MGatner** [sebastianbergmann/diff#101]
I would like to be able to indicate (similar to ~~`git`~~ GitHub) the relative amount a file has changed. I could not find any convenient way to do that currently, other than creating a diff string and calculating the size of the changes. I think it would make a nice addition to this library.

**Comment by MGatner** [comment]
![Screen Shot 2020-05-22 at 2 07 01 PM](https://user-images.githubusercontent.com/17572847/82696753-a4c82000-9c35-11ea-9b32-98d3bf88824c.png)

**Comment by SpacePossum** [comment]
I think the blocks indicates the number of additions and deletions and shown relative to each other, so not relative to the file (either before or after the change).

The number of lines added/deleted is within the result of `Differ::diffToArray` which you could process to the output you want.
Or you can write your own output builder (instance of `DiffOutputBuilderInterface`) and pass to it to the constructor of `Differ` and use the `Differ::diff` method.

If you're thinking about a CI or something like that maybe you can use `diffstat` (https://linux.die.net/man/1/diffstat). This ships with most major linux flavors. So create the diff using the `StrictUnifiedDiffOutputBuilder` and feed the result to the command.

I'm not 100% sure this FR fits in the scope of the project, but I think it could technically be done here if we would know the wanted output format.

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project.

**Comment by MGatner** [comment]
Okay, thanks for the response. Do you know if something like this is calculated anywhere in PHPUnit already?

**Comment by MGatner** [comment]
Thanks @spacepossum, missed your answer until just now! Good starting places.
