### ISSUE TITLE
Support simple colored diffs

### ISSUE THREAD

**Issue by dkarlovi** [sebastianbergmann/diff#114]
When doing this in PHPUnit
```php
static::assertEquals(['aa', 'bb'], ['aa', 'cc']);
```

Output comes out as
```
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'aa'
-    1 => 'bb'
+    1 => 'cc'
 )
 ```
 
 but, if PHPUnit is in color mode, it could come out as
 
 ```diff
 Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'aa'
-    1 => 'bb'
+    1 => 'cc'
 )
 ```

The way to go about it seems like:
1. add color mode to output here
2. make PHPUnit tell Comparator to be in color mode
3. make Comparator pass the information along

Don't know if I'm missing something or if this is the correct repo to create this issue, seems like the correct way forward.

**Comment by SpacePossum** [comment]
I wouldn't increase the scope of the library with output formatters. 

The lib creates strings in the well known/documented `diff` format, this should allow any to process the output and apply what ever operation on it (like adding console coloring and sending it to the console).

**Comment by sebastianbergmann** [comment]
I agree with @SpacePossum.

**Comment by 8ctopus** [comment]
Here's how to do it if you're looking for it:

```sh
composer require codedungeon/php-cli-colors
```

```php
use Codedungeon\PHPCliColors\Color;

$diff = $differ->diff($a, $b);

$replace = [
    '~^([\-\w]*?)$~m' => Color::RED . '$1' . Color::RESET,
    '~^([\+\w]*?)$~m' => Color::GREEN . '$1' . Color::RESET,
];

echo preg_replace(array_keys($replace), array_values($replace), $diff);
```

**Comment by SpacePossum** [comment]
another sample can be found here if using Symfony console:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/627692f794d35c43483f34b01d94740df2a73507/src/Differ/DiffConsoleFormatter.php#L37
