### ISSUE TITLE
Diff lines decorator

### ISSUE THREAD

**Issue by Soullivaneuh** [sebastianbergmann/diff#32]
The idea is to create a `DiffLinesDecorator` interface that will be called here: https://github.com/sebastianbergmann/diff/blob/13edfd8706462032c2f52b4b862974dd46b71c9e/src/Differ.php#L106-L112

This will permit users to easily customize the diff rendering, like I did here: https://travis-ci.org/sonata-project/dev-kit/builds/127322216#L246

What do you think? I could work on a PR for that.

**Comment by nochso** [comment]
Hi!

I've recently worked on a fork to allow things like that: https://github.com/nochso/diff
Essentially you pass a Diff object to a renderer. There are basic templates/renderers for HTML, Text and colored POSIX/CLI output.

**Comment by Soullivaneuh** [comment]
@nochso Interesting, but why not proposing PR instead of a new package?

**Comment by nochso** [comment]
The fork and its public API have changed too much. I've mostly kept the original diff/LCS implementation intact, but everything surrounding it has changed.

So I doubt Sebastian would accept that as a simple PR. However I'm open to merging it for a BC-breaking 2.0 release. @sebastianbergmann, what do you think? Are you interested in merging my changes for a 2.0 release or should it live as a separate library?

Anyway, for now I haven't shared or tagged the fork. I'll gladly tag it unless you find some glaring issue so feel free to try it and report back. Right now you'll have to `composer require nochso/diff:dev-master`

**Comment by sebastianbergmann** [comment]
I would like to keep this component as simple as possible. Therefore, I am afraid that I have to reject this idea. Sorry.
