### ISSUE TITLE
Make Parser method statics

### ISSUE THREAD

**Issue by Soullivaneuh** [sebastianbergmann/diff#71]
The `Parser` class does not manage any internal property and just has two pars method.

Making them static would make more senses and would make a simpler usage:

```php
$diffs = Parser::parse($diffsContent);
```

**Comment by sebastianbergmann** [comment]
The world is a better place for every method that is not static.

**Comment by Soullivaneuh** [comment]
> The world is a better place for every method that is not static.

Well, would you mind to elaborate a bit? :-)
