### ISSUE TITLE
Highlight word-level changes on a line

### ISSUE THREAD

**Issue by arvindpdmn** [sebastianbergmann/diff#77]
Suppose I delete a couple of words near the start of a line. On the same line towards the end, I add a couple of words. The diff program just shows that the old line is deleted and new line is added.

It would be nice just to highlight changes at word level.

I found one alternative diff programs and it has the same problem: https://github.com/chrisboulton/php-diff

I later found another diff that does what I want (word-level highlighting) but it's too slow. It takes 40+ seconds for a small file of about 100 lines and 1500 words: https://github.com/caxy/php-htmldiff

I want to know if there's an config option that turns on word-level diff. Thx

**Comment by sebastianbergmann** [comment]
This is not supported by this component.

**Comment by arvindpdmn** [comment]
Thx for the quick response
