### ISSUE TITLE
FR: add array keys in return from `diffToArray`

### ISSUE THREAD

**Issue by edalzell** [sebastianbergmann/diff#81]
Thanks for this addon, it's amazing!

I'm trying to display the differences in two arrays but having a hard time figuring out which `key`s changed because only the values are returned.

It would be amazing if this was returned:
```
array:6 [▼
  0 => array:2 [▼
    0 => "phone"
    1 => "6045551212"
    2 => 0
  ]
  1 => array:2 [▼
    0 => "id"
    1 => "39a933d8-9879-424b-8620-852079cdb138"
    2 => 0
  ]
```

or even a key/value array:
```
"key" => "phone"
"value" => "6045551212"
"diff" => 1
```

**Comment by edalzell** [comment]
Just about to hop back into this project, is this likely to get addressed?

**Comment by SpacePossum** [comment]
Hi,

Looking at the current code it is really based on creating diffs between strings and about parsing such diff back into some representation (think of it as a `patch` / `udiff` library for PHP).
Making a diff between to different array's might not give the result you are looking for, as `diffToArray` expects the given arrays to represent lines of texts.

Not to worry yet as you might be interested in;
https://github.com/sebastianbergmann/comparator
which has a [ArrayComparator](https://github.com/sebastianbergmann/comparator/blob/3.0.1/src/ArrayComparator.php) .

As for comparing arrays and creating some (abstract) difference between such arrays is the job of a `comparator`, 
(when you got two text representations generated by the `comparator` you could than use this package to create a diff out of it but that is "too late" for your use case)
this `creating` part of it might be what you want to re-use and tweak :)

**Comment by edalzell** [comment]
Thanks I'll take a look.
