### ISSUE TITLE
Not working with symfony/process 5.x

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/diff#90]
See https://travis-ci.org/sebastianbergmann/diff/jobs/627654708.

**Comment by SpacePossum** [comment]
that is only the test failing? odd it wasn't spotted in https://github.com/sebastianbergmann/diff/pull/88 , we only need SF 4 and 5 and can remove the 2 and 3 option

**Comment by GrahamCampbell** [comment]
> odd it wasn't spotted in #88

Because composer actually installed symfony/process v4.3.8 for that test run.

**Comment by SpacePossum** [comment]
yeah, figures, thanks :+1:
